name: docfinder
description: A flutter project to book doctor appointment
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  collection: ^1.17.2
  cupertino_icons: ^1.0.6
  dio: ^4.0.6
  google_fonts: ^6.1.0
  meta: ^1.9.1
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  json_annotation: ^4.8.1
  intl: ^0.18.1

dependency_overrides:
  analyzer: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  very_good_analysis: ^5.1.0
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true
